// AUTO-GENERATED by tools/generate_ts_contracts.py
// Do not edit manually; run `npm run generate:api-types` instead.

export interface RestaurantListItem {
  id: string;
  name: string;
  cuisine?: string[];
  city: string;
  slug?: string | null;
  cover_photo?: string | null;
  timezone?: string | null;
  neighborhood?: string | null;
  address?: string | null;
  short_description?: string | null;
  price_level?: string | null;
  tags?: string[];
  average_spend?: string | null;
}

export interface Restaurant {
  id: string;
  name: string;
  slug?: string | null;
  cuisine?: string[];
  city?: string;
  timezone?: string;
  address?: string | null;
  phone?: string | null;
  photos?: string[];
  cover_photo?: string | null;
  short_description?: string | null;
  neighborhood?: string | null;
  price_level?: string | null;
  tags?: string[];
  highlights?: string[];
  map_images?: string[];
  latitude?: number | null;
  longitude?: number | null;
  directions_url?: string | null;
  menu_url?: string | null;
  instagram?: string | null;
  whatsapp?: string | null;
  average_spend?: string | null;
  dress_code?: string | null;
  experiences?: string[];
  areas?: Area[];
}

export interface Area {
  id: string;
  name?: string | null;
  tables?: Table[];
}

export interface Table {
  id: string;
  name?: string | null;
  capacity?: number;
  position?: [number, number] | null;
  shape?: "circle" | "rect" | "booth" | "pod" | null;
}

export interface Reservation {
  id: string;
  restaurant_id: string;
  party_size: number;
  start: string;
  end: string;
  guest_name: string;
  guest_phone?: string | null;
  table_id?: string | null;
  status?: "booked" | "cancelled";
  arrival_intent?: ArrivalIntent | null;
  prep_eta_minutes?: number | null;
  prep_request_time?: string | null;
  prep_items?: string[] | null;
  prep_scope?: "starters" | "full" | null;
  prep_status?: "pending" | "accepted" | "rejected" | null;
  prep_policy?: string | null;
}

export interface ReservationCreate {
  restaurant_id: string;
  party_size: number;
  start: string;
  end: string;
  guest_name: string;
  guest_phone?: string | null;
  table_id?: string | null;
}

export interface ArrivalIntent {
  status?: "idle" | "requested" | "queued" | "approved" | "rejected" | "cancelled";
  lead_minutes?: number | null;
  prep_scope?: "starters" | "mains" | "full" | null;
  eta_source?: "user" | "prediction" | "location" | null;
  last_signal?: string | null;
  share_location?: boolean;
  notes?: string | null;
  auto_charge?: boolean;
  predicted_eta_minutes?: number | null;
  predicted_eta_seconds?: number | null;
  typical_eta_minutes?: number | null;
  confirmed_eta_minutes?: number | null;
  current_location?: Record<string, number> | null;
  last_location?: Record<string, number> | null;
  route_distance_km?: number | null;
  route_summary?: string | null;
  traffic_condition?: "smooth" | "moderate" | "heavy" | "severe" | "unknown" | null;
  traffic_source?: "gomap" | "osrm" | "fallback" | null;
  traffic_updated_at?: string | null;
}

export interface ArrivalIntentRequest {
  lead_minutes: number;
  prep_scope?: "starters" | "mains" | "full";
  share_location?: boolean;
  eta_source?: "user" | "prediction" | "location";
  auto_charge?: boolean;
  notes?: string | null;
}

export interface ArrivalIntentDecision {
  action: "approve" | "queue" | "reject" | "cancel";
  notes?: string | null;
}

export interface ArrivalLocationPing {
  latitude: number;
  longitude: number;
}

export interface ArrivalEtaConfirmation {
  eta_minutes: number;
}

export interface ArrivalLocationSuggestion {
  id: string;
  name: string;
  address?: string | null;
  latitude: number;
  longitude: number;
  distance_km?: number | null;
  eta_minutes?: number | null;
  eta_seconds?: number | null;
  route_summary?: string | null;
  provider?: string;
}
